{
    "dataType": "CVE_RECORD",
    "cveMetadata": {
        "state": "PUBLISHED",
        "cveId": "CVE-2025-29606",
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "dateUpdated": "2025-07-14T04:14:43.773Z",
        "dateReserved": "2025-03-11T00:00:00.000Z",
        "datePublished": "2025-07-14T00:00:00.000Z"
    },
    "containers": {
        "cna": {
            "providerMetadata": {
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre",
                "dateUpdated": "2025-07-14T04:14:43.773Z"
            },
            "descriptions": [
                {
                    "lang": "en",
                    "value": "py-libp2p before 0.2.3 allows a peer to cause a denial of service (resource consumption) via a large RSA key."
                }
            ],
            "affected": [
                {
                    "vendor": "n/a",
                    "product": "n/a",
                    "versions": [
                        {
                            "version": "n/a",
                            "status": "affected"
                        }
                    ]
                }
            ],
            "references": [
                {
                    "url": "https://github.com/libp2p/py-libp2p/issues/526"
                },
                {
                    "url": "https://github.com/libp2p/py-libp2p/pull/531/files"
                },
                {
                    "url": "https://github.com/libp2p/py-libp2p/compare/v0.2.2...v0.2.3"
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "type": "text",
                            "lang": "en",
                            "description": "n/a"
                        }
                    ]
                }
            ]
        }
    },
    "dataVersion": "5.1"
}